title: Inhaltsseite

status:
  draft: Entwurf
  unlisted: Unsichtbar
  # listed: Veröffentlicht


tabs:
  content:
    label: Inhalt
    fields:
      teasertext:
        label: Teaser Text
        type: textarea
        size: small
        buttons: false
      content:
        label: Inhalt
        type: blocks
        fieldsets:
          text:
            label: Text
            type: group
            fieldsets:
              - heading
              - text
              - list
          media:
            label: Medien
            type: group
            fieldsets:
              - img
              - img-slider
              - youtube
 media:
  label: Medien
  sections:
    files:
      label: Dateien
      type: files
      layout: cards
      size: tiny
